name: Build CLEO iOS .dylib

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-05-01
          targets: aarch64-apple-ios

      - name: Build Project (Release)
        run: cargo build --release --target aarch64-apple-ios

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cleo-dylib
          path: target/aarch64-apple-ios/release/*.dylib
